import { Raleway } from "next/font/google";
import "./globals.css";

// Import Raleway font from Google
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  variable: "--font-raleway",
});

export const metadata = {
  title: "Home Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
