import { Raleway } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import GlobalProvider from "@/Context/GlobalContext";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  variable: "--font-raleway",
});

export const metadata = {
  title: "Home Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <NextTopLoader color="#F9AA58" />
        <Toaster />
        <GlobalProvider>
          <div className="h-screen flex flex-col">
            <Header />
            <div className="flex-grow">
              {children}
            </div>
            <Footer />
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
